function fireNetSeerTrigger(){window.netseer_fire_on_trigger=null;netseerMainFunction(window)}
function netseerMainFunction(k){function w(a,b){var f=new Image;A+1<B.length&&(f.onload=function(){w(a,b)},f.onerror=function(){w(a,b)},f.onabort=function(){w(a,b)});var d="",c="",e=B[A++];k.netseer_cookie&&(d="&cookie=0");31===e&&(c="&ui=2");f.src=39===e?function(){var a=u(window)+"cmi.netseer.com/pixelmatch?ex=39&xid=__UID__&t="+C,a=encodeURIComponent(a),b="ssum";"https://"===u(window)&&(b="ssum-sec");return u(window)+b+".casalemedia.com/usermatchredir?s=183876&cb="+a}():u(window)+"cmi.netseer.com/redirect?ex="+
e+"&t="+C+d+c}function E(a,b,f){var d="";f&&(d=new Date,d.setDate(d.getDate()+f),d="; expires="+d.toUTCString());document.cookie=a+"="+b+d+"; path=/"}function F(a){a+="=";for(var b=document.cookie.split(";"),f=0;f<b.length;f++){for(var d=b[f];" "==d.charAt(0);)d=d.substring(1,d.length);if(0==d.indexOf(a))return d.substring(a.length,d.length)}return null}function q(a,b,f,d){null==f&&(f="");null==d&&(d="&");a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=(new RegExp("[\\?"+d+"]"+a+"=([^"+d+"#]*)")).exec(b);
return null==a?f:a[1]}function u(a){var b="http://";a&&a.location&&a.location.protocol&&"https:"==a.location.protocol.toString().toLowerCase()?b="https://":a&&a.netseer_enforce_protocol&&"https"==a.netseer_enforce_protocol?b="https://":a&&a.netseer_page_url&&"https"==a.netseer_page_url.toLowerCase().substring(0,5)?b="https://":!a||"1"!=a.netseer_ssl&&"true"!=a.netseer_ssl||(b="https://");return b}function x(a){var b=u(a);a.netseer_endpoint?"contextlinks.netseer.com"==a.netseer_endpoint?a.netseer_endpoint=
"cl.netseer.com":"staging.netseer.com"==a.netseer_endpoint&&(a.netseer_endpoint="media.netseer.com"):a.netseer_endpoint=a&&"px"==a.netseer_task?"pixel.netseer.com":"cl.netseer.com";return b+a.netseer_endpoint}function p(a){return null!=a?'"'+a+'"':'""'}function m(a,b){if(a){b&&(a=a.replace(/\+/g," "));try{return"function"==typeof decodeURIComponent?decodeURIComponent(a):unescape(a)}catch(f){return""}}else return a}function c(a,b){if(b){var f="&";k.netseer_global_fparam&&"true"==k.netseer_global_fparam&&
(f="");k.netseer_ad_url+=f+a+"="+b;k.netseer_global_fparam="false"}}function y(a,b){b&&(k.netseer_page_params&&""!=k.netseer_page_params&&(k.netseer_page_params+="&"),k.netseer_page_params+=a+"="+b)}function G(a){a&&(k.netseer_page_params+="&"+a)}function h(a,b){if(b){var f;if(b)try{f="function"==typeof encodeURIComponent?encodeURIComponent(b):escape(b)}catch(d){f=""}else f=b;c(a,f)}}function H(a){a.netseer_global_fparam=null;a.netseer_query=null;a.netseer_ad_frameborder=null;a.netseer_ad_format=
null;a.netseer_page_url=null;a.netseer_output_format=null;a.netseer_language=null;a.netseer_gl=null;a.netseer_hints=null;a.netseer_safe=null;a.netseer_encoding=null;a.netseer_ad_output=null;a.netseer_max_num_ads=null;a.netseer_ad_channel=null;a.netseer_contents=null;a.netseer_adtest=null;a.netseer_kw_type=null;a.netseer_kw=null;a.netseer_num_radlinks=null;a.netseer_max_radlink_len=null;a.netseer_rl_filtering=null;a.netseer_rl_mode=null;a.netseer_rt=null;a.netseer_ad_type=null;a.netseer_image_size=
null;a.netseer_skip=null;a.netseer_page_location=null;a.netseer_referrer_url=null;a.netseer_ad_region=null;a.netseer_ad_section=null;a.netseer_bid=null;a.netseer_cpa_choice=null;a.netseer_cust_age=null;a.netseer_cust_gender=null;a.netseer_cust_interests=null;a.netseer_cust_id=null;a.netseer_cust_job=null;a.netseer_cust_u_url=null;a.netseer_sim=null;a.netseer_color_bilboard=null;a.netseer_banner_id=null;a.netseer_network_id=null;a.netseer_tracking_url=null;a.netseer_tracking_url_encoded=null;a.netseer_page_url_key=
null;a.netseer_search_current_url=null;a.netseer_page_params=null;a.netseer_page_url_base64=null;a.netseer_landing_page_type=null;a.netseer_background_color=null;a.netseer_click_target=null;a.netseer_pixel_param1=null;a.netseer_pixel_param2=null;a.netseer_pixel_param3=null;a.netseer_pixel_id=null;a.netseer_tag_id=null;a.netseer_client_id=null;a.netseer_task=null;a.netseer_creative_id=null;a.netseer_auction_id=null;a.netseer_slot_index=null;a.netseer_imp_type=null;a.netseer_ext_vid=null;a.netseer_advs=
null;a.netseer_taglink_id=null;a.netseer_inview_taglink_id=null;a.netseer_segment=null;a.netseer_iframe_buster=null;a.netseer_search_param=null;a.netseer_recirculation_sites=null;a.netseer_fire_on_trigger=null;a.netseer_redundant_params=null;a.netseer_url_pattern=null;a.netseer_theme_id=null;a.netseer_imp_src=null;a.netseer_endpoint=null;a.netseer_ad_height=null;a.netseer_ad_width=null;a.netseer_page_url_key=null;a.netseer_debug=null;a.netseer_pixel_cpa=null;a.netseer_search_term=null;a.netseer_visitor_cookie=
null;a.netseer_cookie=null;a.netseer_hints=null;a.netseer_bing_formcode=null;a.netseer_embed_external_pixels=null;a.netseer_referrer_search_term=null;a.netseer_referrer_domain=null;a.netseer_concept_group_id=null;a.netseer_ext_params=null;a.netseer_url_suffix=null;a.netseer_embed_style=null;a.netseer_append=null;a.netseer_pilot_id=null;a.netseer_rule_id=null;a.netseer_enforce_protocol=null;a.netseer_lead_params=null;a.netseer_ip=null;a.netseer_num_ads=null;a.netseer_ad_position=null;a.netseer_cpc=
null;a.netseer_user_tgid=null;a.netseer_page_tgid=null;a.netseer_user_cgid=null;a.netseer_page_cgid=null;a.netseer_image_size=null;a.netseer_image_forced=null;a.netseer_cookie_matching=null;a.netseer_req_id=null;a.netseer_ext_script=null;a.netseer_pixel_trigger_mode=null;a.netseer_back_fill=null;a.netseer_referred_client_id=null;a.netseer_search_time=null;a.netseer_engine_type=null;a.netseer_flow_id=null;for(var b=0;b<v.length;b++)a[v[b]]=null;for(b=0;b<r.length;b++)a[r[b]]=null}function I(a,b,f,
d,c,e,h,l,k,m,u,q,v,t,r,x){d=Math.random();c=c.substring(0,2083);c=c.replace(/%\w?$/,"");null!=c&&(c=c+"&t="+d);"lp"==a?(b='<iframe  id="netseer_landingpage_frame"  name="netseer_landingpage_frame" width='+p(f)+" height="+p(b)+" src="+p(c)+' frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no"></iframe>',document.getElementById(e).innerHTML=b):"ad"==a?(a=document,t&&"dfp_outofpage"===t?a=window.parent.document:t&&"iframe_buster"===t&&(a=window.parent.parent.document),
t=a.getElementById(e),v&&"js"==v||x?(b=document.createElement("script"),b.type="text/javascript",b.async=!0,b.src=c,t&&t.appendChild(b)):(b='<iframe name="netseer_ads_frame" width='+p(f)+" height="+p(b)+" src="+p(c)+' frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no"></iframe>',t&&(t.innerHTML=b)),b=F("netseer_cm"),"false"!=u&&"done"!=b&&!h&&"10"!=l&&(null==r||isNaN(parseInt(r))||100>parseInt(r))&&(w(l),"11"!=l&&"12"!=l&&"13"!=l&&"14"!=
l&&"15"!=l&&"16"!=l&&"17"!=l&&"18"!=l&&"20"!=l&&"21"!=l&&"27"!=l&&E("netseer_cm","done",15))):"px"==a&&(q&&"sync"==q?D(c,k,m,e,l):J(function(){D(c,k,m,e,l)}))}function J(a){function b(){c||(c=!0,a())}var c=!1;if("complete"===document.readyState||"interactive"===document.readyState)b();else if(window.addEventListener)window.addEventListener("load",b,!1);else if(document.addEventListener)document.addEventListener("DOMContentLoaded",b,!1);else if(document.attachEvent){try{var d=null!=window.frameElement}catch(g){}if(document.documentElement.doScroll&&
!d){var e=function(){if(!c)try{document.documentElement.doScroll("left"),b()}catch(a){setTimeout(e,10)}};e()}document.attachEvent("onreadystatechange",function(){"complete"===document.readyState&&b()})}}function D(a,b,c,d,g){var e=new Image;e.onload=function(){w(g,d)};e.onerror=function(){w(g,d)};e.onabort=function(){w(g,d)};e.src=a;"undefined"!=typeof b&&K(b,c,d)}function K(a,b,c){a='<iframe name="nspx" width=0 height=0 src='+p(b+"/dsatserving2/servlet/pixel?pxid="+a)+' frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no"></iframe>';
(b=document.getElementById(c))?b.innerHTML=a:(b=document.createElement("ins"),b.style.cssText="display:inline-table;border:none;height:0;width:0;;margin:0;padding:0;position:relative;visibility:hidden",b.setAttribute("id",c),b.innerHTML=a,document.documentElement.lastChild.appendChild(b))}function L(a){if(a.netseer_redundant_params)for(var b=a.netseer_redundant_params.split(","),c=0;c<b.length;c++){var d=a.netseer_page_url,g=b[c],d=String(d),e=new RegExp("\\?"+g+"=[^&]*&?","gi"),d=d.replace(e,"?"),
e=new RegExp("\\&"+g+"=[^&]*&?","gi"),d=d.replace(e,"&"),d=d.replace(/(\?|&)$/,"");a.netseer_page_url=d}}function M(a){if(a.netseer_url_pattern){var b=(new RegExp(a.netseer_url_pattern,"gi")).exec(a.netseer_page_url);null!=b&&(a.netseer_page_url=m(b[1]))}}function N(){function a(a){a=a.match(/[\d]+/g);a.length=3;return a.join(".")}var b=!1,c="";if(navigator.plugins&&navigator.plugins.length){var d=navigator.plugins["Shockwave Flash"];d&&(b=!0,d.description&&(c=a(d.description)));navigator.plugins["Shockwave Flash 2.0"]&&
(b=!0,c="2.0.0.11")}else if(navigator.mimeTypes&&navigator.mimeTypes.length)(b=(d=navigator.mimeTypes["application/x-shockwave-flash"])&&d.enabledPlugin)&&(c=a(d.enabledPlugin.description));else try{d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),b=!0,c=a(d.GetVariable("$version"))}catch(g){try{d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),b=!0,c="6.0.21"}catch(e){try{d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),b=!0,c=a(d.GetVariable("$version"))}catch(h){}}}return b&&c}function O(a){(new Date).getTime();
a.netseer_page_params="";a.netseer_global_fparam="true";L(a);M(a);var b=a.netseer_page_url;if("lp"==a.netseer_task){a.netseer_ad_url=x(a)+"/dsatserving2/servlet/search?";var f=a.location.search.substring(1);f&&(f=f.replace("tlid=","tlidr="));q("tlid",f,null,null);c("tlid",a.netseer_is_inview?a.netseer_inview_taglink_id:a.netseer_taglink_id);f&&(k.netseer_ad_url+="&"+f);h("url",b)}else"ad"==a.netseer_task?(a.netseer_ad_url=x(a)+"/dsatserving2/servlet/BannerServer?",a.netseer_ad_endpoint&&(a.netseer_ad_url=
u(a)+a.netseer_ad_endpoint,a.netseer_ad_url+="?nlt=AD_REQUEST&"),c("tagid",a.netseer_tag_id),c("tlid",a.netseer_is_inview?a.netseer_inview_taglink_id:a.netseer_taglink_id),c("cid",a.netseer_creative_id),c("cptgid",a.netseer_concept_group_id),c("plid",a.netseer_pilot_id),c("rlid",a.netseer_rule_id),c("utgid",a.netseer_user_tgid),c("ptgid",a.netseer_page_tgid),c("ucgid",a.netseer_user_cgid),c("pcgid",a.netseer_page_cgid),c("bft",a.netseer_back_fill),null!=a.netseer_iframe_buster&&""!=a.netseer_iframe_buster||
h("url",b),c("q",a.netseer_query)):"px"==a.netseer_task&&(a.netseer_ad_url=x(a)+"/dsatserving2/servlet/log?",c("tagid",a.netseer_tag_id),c("tlid",a.netseer_is_inview?a.netseer_inview_taglink_id:a.netseer_taglink_id),c("pxid",a.netseer_pixel_id),a.netseer_log_type||(a.netseer_log_type="ltpx"),c("nlt",a.netseer_log_type),c("cid",a.netseer_creative_id),c("q",a.netseer_query),h("url",b),h("pxp1",a.netseer_pixel_param1),h("pxp2",a.netseer_pixel_param2),h("pxp3",a.netseer_pixel_param3),h("pxcpa",a.netseer_pixel_cpa));
c("thid",a.netseer_theme_id);c("adh",a.netseer_ad_height);c("adw",a.netseer_ad_width);c("imps",a.netseer_imp_src);c("impt",a.netseer_imp_type);c("pp",a.netseer_pcpm);c("auid",a.netseer_auction_id);c("sidx",a.netseer_slot_index);for(b=0;b<v.length;b++)null!=a[v[b]]&&c(P[b],a[v[b]]);for(b=0;b<r.length;b++)null!=a[r[b]]&&h(Q[b],a[r[b]]);h("rfd",a.netseer_referrer_domain);c("evid",a.netseer_ext_vid);y("segment",a.netseer_segment);y("sites",a.netseer_recirculation_sites);y("bingformc",a.netseer_bing_formcode);
G(a.netseer_ext_params);h("nslp",m(a.netseer_lead_params));c("bp",a.netseer_bcpm);a.netseer_cookie&&c("cookie","0");h("sep",a.netseer_search_param);h("set",m(a.netseer_search_term,!0));h("trurl",m(a.netseer_tracking_url));c("advs",a.netseer_advs);h("rfs",m(a.netseer_referrer_search_term,!0));c("frd",a.netseer_first_request_date);c("ip",a.netseer_ip);c("cnads",a.netseer_num_ads);c("adpos",a.netseer_ad_position);c("cpc",a.netseer_cpc);c("cimg",a.netseer_image_size);c("cimgfrc",a.netseer_image_forced);
a.netseer_image_sizeon&&c("imgsizeon",a.netseer_image_sizeon);h("hints",a.netseer_hints);h("extsct",m(a.netseer_ext_script));h("inimgmv",m(a.netseer_image_meta_val));h("inimga",m(a.netseer_img_alt));h("inimgu",m(a.netseer_image_src_url));c("rclid",a.netseer_referred_client_id);c("acdt",a.netseer_search_time);c("engt",a.netseer_engine_type);c("flowid",a.netseer_flow_id);c("pgv_id",a.netseer_pgv_id);c("apid",a.netseer_append_location);c("mresp",a.isMobileResponsive?"1":"0");(a.netseer_embed_style&&
"js"==a.netseer_embed_style||a.hb_behavior)&&c("sid",a.netseer_append_location);a.hb_behavior&&(b=window.NETSEER&&window.NETSEER.encode&&window.NETSEER.encode["int"]||window.btoa||function(a){return a},c("hb_source",a.hb_source||"0"),c("hb_pp",encodeURIComponent(a.hb_pp||b(0))),c("hb_adid",a.hb_adid||"0"),c("hb_bp",encodeURIComponent(a.hb_bp||b(0))),c("hb_eauid",a.hb_eauids||"0"),c("hb_tt",a.hb_tt||"0"),c("hb_to",a.hb_to||"0"),c("hb_rt",a.hb_rt||"0"),c("hb_status",a.hb_status||"NB"),"HEADER_DIRECT"===
a.hb_behavior&&a.hb_adUrls&&(a.netseer_embed_style="header_bidding_iframe",a.netseer_ad_url=a.hb_adUrls));b=N();a.netseer_deployment_type&&"inpage"===a.netseer_deployment_type&&b&&c("flash",b);a.netseer_referrer_url&&2E3>a.netseer_ad_url.length+a.netseer_referrer_url.length&&h("ref",m(a.netseer_referrer_url));h("params",a.netseer_page_params);I(a.netseer_task,a.netseer_ad_height,a.netseer_ad_width,a.netseer_iframe_buster,a.netseer_ad_url,a.netseer_append_location,a.netseer_cookie,a.netseer_imp_src,
a.netseer_pixel_id,x(a),a.netseer_cookie_matching,a.netseer_pixel_trigger_mode,a.netseer_embed_style,a.netseer_deployment_type,a.netseer_imp_type,a.hb_behavior);H(a)}function z(a,b){return b&&a?-1!=b.indexOf(a):!1}function R(a){var b=document,c=b.location,d=b.referrer;null==a.netseer_first_request_date&&(a.netseer_first_request_date=(new Date).getTime());a.netseer_search_current_url=c;var g=null;a.netseer_referrer_url&&(g=a.netseer_referrer_url);d&&(a.netseer_tag_id&&17744==a.netseer_tag_id&&(a.netseer_page_url=
d),g||(g=d));if(g)try{a.netseer_referrer_domain=g.split("/")[2];d=g;g=null;if(z(".google.",d))g=q("q",d,null);else if(z(".bing.",d))g=q("q",d,null);else if(z(".yahoo.",d)){var e=q("p",d,null);if(e)g=e;else{var h=q("q",d,null);h&&(g=h)}}g&&(g=g.replace(/\+/g," "));a.netseer_referrer_search_term=g}catch(k){}document.cookie="testcookie";cookieBlocked=-1!=document.cookie.indexOf("testcookie")?!1:!0;document.cookie="testcookie; expires=Thu, 01 Jan 1970 00:00:01 GMT;";e=navigator.userAgent.toLowerCase();
e=-1!=e.indexOf("safari")&&-1==e.indexOf("chrom")?"Safari":-1!=e.indexOf("mozilla/5.0 (windows nt 6.1; wow64; trident/7.0; rv:11.0) like gecko")?"IE11NoCookie":-1!=e.indexOf("opera")?"Opera":-1!=e.indexOf("staroffice")?"Star Office":-1!=e.indexOf("webtv")?"WebTV":-1!=e.indexOf("beonex")?"Beonex":-1!=e.indexOf("chimera")?"Chimera":-1!=e.indexOf("netpositive")?"NetPositive":-1!=e.indexOf("phoenix")?"Phoenix":-1!=e.indexOf("firefox")?"Firefox":-1!=e.indexOf("skipstone")?"SkipStone":-1!=e.indexOf("msie")?
"Internet Explorer":-1!=e.indexOf("netscape")?"Netscape":-1!=e.indexOf("mozilla/5.0")?"Mozilla":-1!=e.indexOf("/")?"mozilla"!=e.substr(0,e.indexOf("/"))?navigator.userAgent.substr(0,e.indexOf("/")):"Netscape":-1!=e.indexOf(" ")?navigator.userAgent.substr(0,e.indexOf(" ")):navigator.userAgent;0!=cookieBlocked||"Safari"!=e&&"IE11NoCookie"!=e||(cookieBlocked=!0);a.netseer_cookie=cookieBlocked;if(null==a.netseer_page_url){var n;c=a.netseer_page_url_key;if(null==c)try{n=a.top.location.href}catch(p){n=
a.location.href}else n=c.split(","),c="&",3<n.length&&(c=n[3]),c=m(q(n[0],a.location,null,c)),1<n.length&&(c=n[1]+c),2<n.length&&(c+=n[2]),n=c;a.netseer_page_url=n;a.netseer_last_modified_time=Date.parse(b.lastModified)/1E3}else a.netseer_page_location=c,a.netseer_page_url=m(a.netseer_page_url);a.netseer_url_suffix&&(a.netseer_page_url+=a.netseer_url_suffix)}var v="netseer_ssl netseer_carrier_id netseer_lat netseer_long netseer_country netseer_city netseer_zip netseer_region netseer_dma netseer_device_type netseer_platform netseer_handset_id netseer_connection netseer_device_id netseer_site_id netseer_app_id netseer_ext_channel netseer_aud_segment netseer_demo netseer_inv_type netseer_req_id netseer_seller_id netseer_debug".split(" "),
P="ssl caid lat long cntr city zip rgn metro dvtype plf hsid cnn dvid stid appid extch extaseg demo invtype refid exsid dbg".split(" "),r=["netseer_site_name","netseer_app_name"],Q=["stname","appname"],C=(new Date).getHours(),B=[10,11,14,16,27,18,31,39],A=0;window.injectNetseerAd=function(a,b){var c=document.getElementById(a),d='<iframe  id="nsfiframe_'+a+'"  name="netseer_friendly_frame" width='+p(netseer_ad_width)+" height="+p(netseer_ad_height)+' frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no"></iframe>',
g=document.createElement("ins");g.innerHTML=d;c.appendChild(g);iFrame=g.getElementsByTagName("iframe")[0];iFrame.contentDocument.open();iFrame.contentDocument.write(b);iFrame.contentDocument.close()};k.netseer_fire_on_trigger||(R(k),O(k))};
